version: "3.9"

volumes:
    db-data:
      driver: local
  
services:
    myhouse-app: &app
      hostname: app
      image: myhouse_server
      stdin_open: true
      tty: true 
      build: .
      command: bash
      ports:
        - "5050:5050"
      volumes: 
        - .:/usr/app
        - ~/shared_ssh:/root/.ssh
      depends_on:
        - myhouse-db
    
    test:
      <<: *app
      environment:
        NODE_DEV: 'true'
      command: yarn test
  
    myhouse-db:
      hostname: postgres
      image: postgres:11
      environment:
        POSTGRES_PASSWORD: "postgres"
      ports:
        - "4321:5432"
      volumes:
        - db-data:/var/lib/postgresql/data
